/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MeetMeetIdRouteImport } from './routes/meet.$meetId'
import { Route as MeetMeetIdEditRouteImport } from './routes/meet.$meetId_.edit'

const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetMeetIdRoute = MeetMeetIdRouteImport.update({
  id: '/meet/$meetId',
  path: '/meet/$meetId',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetMeetIdEditRoute = MeetMeetIdEditRouteImport.update({
  id: '/meet/$meetId_/edit',
  path: '/meet/$meetId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/meet/$meetId': typeof MeetMeetIdRoute
  '/meet/$meetId/edit': typeof MeetMeetIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/meet/$meetId': typeof MeetMeetIdRoute
  '/meet/$meetId/edit': typeof MeetMeetIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/meet/$meetId': typeof MeetMeetIdRoute
  '/meet/$meetId_/edit': typeof MeetMeetIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/create' | '/meet/$meetId' | '/meet/$meetId/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create' | '/meet/$meetId' | '/meet/$meetId/edit'
  id: '__root__' | '/' | '/create' | '/meet/$meetId' | '/meet/$meetId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  MeetMeetIdRoute: typeof MeetMeetIdRoute
  MeetMeetIdEditRoute: typeof MeetMeetIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meet/$meetId': {
      id: '/meet/$meetId'
      path: '/meet/$meetId'
      fullPath: '/meet/$meetId'
      preLoaderRoute: typeof MeetMeetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meet/$meetId_/edit': {
      id: '/meet/$meetId_/edit'
      path: '/meet/$meetId/edit'
      fullPath: '/meet/$meetId/edit'
      preLoaderRoute: typeof MeetMeetIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  MeetMeetIdRoute: MeetMeetIdRoute,
  MeetMeetIdEditRoute: MeetMeetIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
